georgez/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls'))
]

tugas/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.home,name='index'),
    path('profile/',views.profile,name='story3'),
    path('workinpoggers/',views.workinpoggers,name='wip')
]

tugas/models.py
from django.db import models

# Create your models here.

tugas/forms.py
from django import forms

##Create your forms here

tugas/views.py
from django.shortcuts import render,redirect

# Create your views here.

def home(request):
    return render(request,'pages/index.html',{})
    
def profile(request):
    return render(request, 'pages/story3.html',{})
    
def workinpoggers(request):
    return render(request, 'pages/wip.html',{})

tugas/templates/pages/index.html
{% extends 'template.html' %}

{% block content %}
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
		
<title>Small Blog.</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">



<style>
body,h1,h2,h3,h4,h5 {font-family: "Raleway", sans-serif}
</style>

<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
<div class="w3-content" style="max-width:1400px">

<!-- Header -->
<header class="w3-container w3-center w3-padding-32"> 
  <h1><b>Small blog from ya Boy.</b></h1>
  <p>Welcome, lads! </p>
</header>

<body class="w3-light-grey">

	
	
<!-- Grid -->
<div class="w3-row">

<!-- Blog entries -->
<div class="w3-col l8 s12">
  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
    <img src="static/assets/header.png" alt="Self Potrait" style="width:100%">
    <div class="w3-container">
      <h3><b>About me</b></h3>
      <h5> <span class="w3-opacity">October 2nd, 2020</span></h5>
    </div>

    <div class="w3-container">
      <p>A small introduction, I graduated from high school in 2018 and now I am a Computer Science student in University of Indonesia. 
	Unlike other programmers, in my spare times I love cranking up my favorite songs to the max volume while writing some stories. That's about it really. Yeah... you can go now.</p>
      <div class="w3-row">
        <div class="w3-col m8 s12">          
        </div>
        <div class="w3-col m4 w3-hide-small">
          <p><span class="w3-padding-large w3-right"><b></b> <span class="w3-tag"></span></span></p>
        </div>
      </div>
    </div>
  </div>
  <hr>

  <!-- Blog entry -->
  <div class="w3-card-4 w3-margin w3-white">
  <img src="static/assets/header2.png" alt="Header2" style="width:100%">
    <div class="w3-container">
      <h3><b>Daily Routine</b></h3>
      <h5></h5>
    </div>

    <div class="w3-container">
      <p>I want to share my healthy daily routine, I hope it helps. <br></br><br> - Wake up around 6 AM </br><br> - Get out of your room and proceed to get some breakfast meal thingy. </br>
	    <br> - Stop by a sofa and take another 2 hours nap. </br><br> - Wake up and eat your cold breakfast. </br><br> - Take a shower. </br><br> - Stare at your PC/laptop monitor for 8 hours (more less). </br>
		<br> - Combine lunch and dinner. </br><br> - Sleep. </br><br></br> If you're not convinced enough, this one could work for some people. Click the button below. I definitely NOT search that one on Google.</p>
      <div class="w3-row">
        <div class="w3-col m8 s12">
          <p><a href="https://medicalxpress.com/news/2020-04-healthy-routine-home.html"><button class="w3-button w3-padding-large w3-white w3-border"><b>YES, THIS ONE »</b></button></a></p>
        </div>
        <div class="w3-col m4 w3-hide-small">
          <p><span class="w3-padding-large w3-right"></span></p>
        </div>
      </div>
    </div>
  </div>
<!-- END BLOG ENTRIES -->
</div>

<!-- Introduction menu -->
<div class="w3-col l4">
  <!-- About Card -->
  <div class="w3-card w3-margin w3-margin-top">
  <img src="static/assets/zoza.png" style="width:100%">
    <div class="w3-container w3-white">
      <h4><b>Zovier Zharvan Filhaq</b></h4>
      <p>Hello, I'm Zovier Zharvan (most of my friends called me Zoza or Jorj). I'm 20 and single, so ladies... yeah, you know ;)</p>
    </div>
  </div><hr>
  
  <!-- Posts -->
  <div class="w3-card w3-margin">
    <div class="w3-container w3-padding">
      <h4>Socials</h4>
    </div>
    <ul class="w3-ul w3-hoverable w3-white">
      <li class="w3-padding-16">
	  <a href="https://www.instagram.com/zovierzharvan/">
        <img src="static/assets/insta.png" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Instagram</span><br>
        <span>My Instagram</span>
		</a>
      </li>
      <li class="w3-padding-16">
	  <a href="https://www.youtube.com/watch?v=dQw4w9WgXcQ&ab_channel=RickAstleyVEVO">
        <img src="static/assets/youtube.png" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">YouTube</span><br>
        <span>YouTube Channel</span>
	  </a>
      </li> 
      <li class="w3-padding-16">
	  <a href="https://Google.co.uk/">
        <img src="static/assets/web1.png" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Website</span><br>
        <span>My own go-to website.</span>
	  </a>
      </li>   
      <li class="w3-padding-16 w3-hide-medium w3-hide-small">
	  
	  <a href="https://scele.cs.ui.ac.id">
        <img src="static/assets/web2.png" alt="Image" class="w3-left w3-margin-right" style="width:50px">
        <span class="w3-large">Other Website</span><br>
        <span>This one is only for work purposes.</span>
	  </a>
      </li>  
    </ul>
  </div>
  <hr> 

  
<!-- END Introduction Menu -->
</div>

<!-- END GRID -->
</div><br>

<!-- END w3-content -->
</div>

<!-- Footer -->
<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
    <a href="https://en.wikipedia.org/wiki/Y%C5%8Dichi_Takahashi"><button class="w3-button w3-black w3-padding-large w3-margin-bottom">Something Interesting »</button></a>
  <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

</body>
{% endblock %}

tugas/templates/pages/story3.html
{% extends 'template.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/main.css' %}">
<meta http-equiv="pragma" content="no-cache" />
<title>My Page.</title>
<!-- Start of page content -->


<!-- Text landing -->
<div class="container">
    <img src="{% static 'assets/zoza.png' %}" class="gambar">
    <div class="heroText">
        Zovier Zharvan Filhaq
    </div>
    <div>
        Sedikit tentang saya, saya mahasiswa Fasilkom UI angkatan 2018 yang berasal dari SMA Kharisma Bangsa. Hobi saya menulis cerita. Sekian.
    </div>
</div>

<div class="container2">
	<div>
	    <a href="{%url 'main:index' %}"> Klik disini untuk pindah ke Blog yang lebih bagus. </a>
	</div>
</div>

{% endblock %}

tugas/templates/pages/wip.html
{% extends 'template.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'css/main.css' %}">
<meta http-equiv="pragma" content="no-cache" />

<title>Work In Progress..</title>

<div class="container">
<img src="{% static 'assets/gibson.png' %}">
    <div>
        This page is still under construction.
    </div>
</div>

{% endblock %}

tugas/templates/template.html
{% load static %}
<!DOCTYPE html>
<html>
	<head>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
	</head>
	
	<nav class="navbar navbar-expand navbar-dark bg-dark">
		<a href="{%url 'main:index' %}" class="navbar-brand">Home</a>
		<div class="collapse navbar-collapse">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item">
					<a href="{%url 'main:story3' %}" class="nav-link"> Old Site </a>
				</li>
				<li class="nav-item">
					<a href="{%url 'main:wip' %}" class="nav-link"> WIP </a>
				</li>
			</ul>
		</div>
	</nav>
		<div class="wrapper">
			{% block content %}
			{% endblock %}
		</div>
	</html>